---
title: "RQ4: How can we accurately estimate energy consumption before training DL models for image classification?"
subtitle: "Analysis of energy consumption metrics for Inception V3 architecture"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float: true
    code_folding: hide
    theme: journal
    df_print: paged
author: "Santiago del Rey"
knit: internalRmdTools::knit_to_reports
---

```{r setup, include=FALSE}
knitr::opts_knit$set(
    root.dir = "../"
)
library(arrow)
library(patchwork) # for combining plots
library(ggplot2)
library(ggpubr) # for publication-ready plots
library(viridis)
library(showtext)
library(tidyverse)
```

```{r setup-fonts, include=FALSE}
# For discrete variables
viridis_scheme <- "turbo"
options(
    ggplot2.discrete.fill = function(...) scale_fill_viridis_d(..., option = viridis_scheme),
    ggplot2.discrete.colour = function(...) scale_colour_viridis_d(..., option = viridis_scheme)
)

# For continuous variables
options(
    ggplot2.continuous.fill = function(...) scale_fill_viridis_c(..., option = viridis_scheme),
    ggplot2.continuous.colour = function(...) scale_colour_viridis_c(..., option = viridis_scheme)
)

font_add("CMU Serif", regular = "cmunrm.ttf") # You need the font installed
showtext_auto()

theme_set(theme_pubr(base_family = "CMU Serif") +
    theme(
        plot.title = element_text(size = 24, face = "bold", hjust = 0.5),
        axis.title = element_text(size = 18),
        axis.text = element_text(size = 16),
        legend.text = element_text(size = 16),
        strip.text = element_text(size = 18),
        legend.position = "top"
    ))

pub_theme <- theme(
    plot.title = element_text(size = 11, face = "bold", hjust = 0.5),
    axis.title = element_text(size = 10),
    axis.text = element_text(size = 9),
    legend.title = element_text(size = 10),
    legend.text = element_text(size = 9),
    strip.text = element_text(size = 10)
)
```

```{r create-figures-directory, include=FALSE}
fig_dir <- "reports/figures/RQ4/"
print(getwd())
if (!dir.exists(fig_dir)) {
    dir.create(fig_dir, recursive = TRUE)
}
```

## Load data
```{r load-agg-data, include=FALSE}
df <- read_parquet("data/metrics/processed/clean-dl-training-energy-consumption-dataset.gzip") %>%
    rename(
        energy = `energy (MJ)`,
        power_draw = `average gpu power (W)`,
        batch_size = `batch size`,
        image_size = `image size`,
        allocated_ram = `total ram (GB)`,
        training_environment = `training environment`,
    ) %>%
    mutate(
        energy_per_image = (energy * 1000000) / `total seen images`, # Convert MJ to J and normalize by total seen images
        epoch_duration = `training duration (h)` / `trained epochs` * 3600, # Calculate average epoch duration in seconds
        batch_size = factor(batch_size, levels = c("32", "64", "256")),
        input_size = factor(image_size, levels = c("(75, 75)", "(128, 128)", "(224, 224)")),
        dataset = factor(dataset),
        dataset = case_match(
            dataset,
            "stanford_dogs" ~ "Stanford Dogs",
            "caltech101" ~ "Caltech 101"
        ),
        training_environment = factor(training_environment, levels = c("Desktop Normal User", "Desktop ML Engineer", "Server")),
    ) %>%
    select(run_id, energy_per_image, power_draw, epoch_duration, batch_size, input_size, dataset, training_environment, allocated_ram)
```
```{r load-data-energy-regimes}
regimes_df <- read_parquet("data/analysis/processed/regimes.gzip")

regimes_df <- regimes_df %>%
    rename(
        stabilizing_epoch = `stabilizing epoch`,
    ) %>%
    inner_join(df %>% select(run_id, training_environment), by = "run_id")

regimes_df
```

### Plot the cumulative distribution of stabilizing epochs for each training environment
```{r plot-cumulative-distribution, echo=FALSE, fig.width=10, fig.height=2.75}
# Prepare data for ECDF lines
all_ecdf <- regimes_df %>%
    count(stabilizing_epoch) %>%
    arrange(stabilizing_epoch) %>%
    mutate(cum_pct = cumsum(n) / sum(n))

env_ecdf <- regimes_df %>%
    group_by(training_environment, stabilizing_epoch) %>%
    tally() %>%
    arrange(training_environment, stabilizing_epoch) %>%
    group_by(training_environment) %>%
    mutate(cum_pct = cumsum(n) / sum(n))

cumm_plot <- ggplot() +
    # Per-environment ECDFs
    geom_line(
        data = env_ecdf,
        aes(x = stabilizing_epoch, y = cum_pct, color = training_environment, linetype = "Environment"),
        linewidth = 1
    ) +
    # All ECDF
    geom_line(
        data = all_ecdf,
        aes(x = stabilizing_epoch, y = cum_pct, color = "All", linetype = "All"),
        linewidth = 1
    ) +
    # 90% line
    geom_hline(
        aes(yintercept = 0.9, color = "90%", linetype = "90%"),
        linewidth = 1
    ) +
    scale_color_manual(
        name = NULL,
        values = c(
            "Desktop Normal User" = "#21908CFF",
            "Desktop ML Engineer" = "#440154",
            "Server" = "#FDE725FF",
            "All" = "orange",
            "90%" = "black"
        ),
        breaks = c("Desktop Normal User", "Desktop ML Engineer", "Server", "All", "90%"),
        labels = c("Desktop Normal User", "Desktop ML Engineer", "Server", "All", "90%")
    ) +
    scale_linetype_manual(
        name = NULL,
        values = c(
            "Environment" = "solid",
            "All" = "dashed",
            "90%" = "dashed"
        ),
        breaks = c("Environment", "All", "90%"),
        labels = c("Environment", "All", "90%")
    ) +
    labs(
        x = "Stabilizing epoch",
        y = "Cumulative percentage of\ntraining executions"
    ) +
    scale_x_continuous(breaks = seq(0, max(regimes_df$stabilizing_epoch), by = 10)) +
    guides(
        color = guide_legend(
            override.aes = list(linetype = c("solid", "solid", "solid", "dashed", "dashed")),
            ncol = 1
        ),
        linetype = "none"
    ) +
    theme(
        legend.position = "inside",
        legend.justification = c("right", "bottom"),
        legend.box.just = "left",
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_rect(fill = "transparent"),
    )

cumm_plot

ggsave(
    plot = cumm_plot + pub_theme,
    filename = file.path(fig_dir, "stabilizing-epoch-cumulative-distribution.pdf"),
    device = cairo_pdf,
    units = "cm",
    width = 13.71, height = 5, dpi = 300
)
```

## Load energy estimation data
```{r load-energy-estimation-data}
energy_estimation_data <- read_parquet("data/analysis/processed/energy-estimation-from-first-epochs.gzip")
energy_estimation_data
```
```{r load-energy-estimation-by-epoch-start}
energy_estimation_by_epoch_start <- read_parquet("data/analysis/processed/energy-estimation-by-epoch-start.gzip")
energy_estimation_by_epoch_start
```

## Compute the RMSE for each training environment
```{r compute-rmse-by-window-size}
rmse_df <- energy_estimation_data %>%
    group_by(`window size`) %>%
    summarise(
        rmse_method_1 = sqrt(mean((`estimated total energy (kJ) (online power-based)` - `total energy (kJ)`)^2)),
        rmse_method_2 = sqrt(mean((`estimated total energy (kJ) (online epoch-energy-based)` - `total energy (kJ)`)^2)),
        .groups = "drop"
    )

rmse_window_plot <- ggplot(rmse_df, aes(x = `window size`)) +
    geom_line(aes(y = rmse_method_1, color = "STEP-P"), linewidth = 0.5) +
    geom_line(aes(y = rmse_method_2, color = "STEP-E"), linetype = "dashed", linewidth = 0.5) +
    labs(
        x = "Window size (epochs)",
        y = "RMSE (kJ)",
        title = "RMSE of energy estimation vs. window size"
    ) +
    scale_color_manual(
        name = NULL,
        values = c("STEP-P" = "#440154FF", "STEP-E" = "#21908CFF")
    )

rmse_window_plot
```

```{r compute-rmse-by-epoch}
rmse_df <- energy_estimation_by_epoch_start %>%
    group_by(`stabilizing epoch`) %>%
    summarise(
        rmse_method_1 = sqrt(mean((`estimated energy (kJ) (online power-based)` - `total energy (kJ)`)^2)),
        rmse_method_2 = sqrt(mean((`estimated energy (kJ) (online epoch-energy-based)` - `total energy (kJ)`)^2)),
        .groups = "drop"
    )

rmse_epoch_plot <- ggplot(rmse_df, aes(x = `stabilizing epoch`)) +
    geom_line(aes(y = rmse_method_1, color = "STEP-P"), linewidth = 0.5) +
    geom_line(aes(y = rmse_method_2, color = "STEP-E"), linetype = "dashed", linewidth = 0.5) +
    labs(
        x = "Stabilizing epoch",
        y = "RMSE (kJ)",
        title = "RMSE of energy estimation vs. stabilizing epoch"
    ) +
    scale_color_manual(
        name = NULL,
        values = c("STEP-P" = "#440154FF", "STEP-E" = "#21908CFF")
    )

rmse_epoch_plot
```

```{r combine-rmse-plots, echo=FALSE}
rmse_window_plot <- rmse_window_plot + theme(
    legend.position = "inside",
    legend.justification = c("right", "top"),
    legend.box.just = "left",
    legend.margin = margin(0, 0, 0, 0),
    legend.background = element_rect(fill = "transparent")
)

rmse_epoch_plot <- rmse_epoch_plot + theme(
    legend.position = "none",
)

combined_rmse_plot <- (rmse_window_plot / rmse_epoch_plot) & pub_theme

ggsave(
    plot = combined_rmse_plot,
    filename = file.path(fig_dir, "energy-estimation-vs-window-size-and-stabilizing-epoch.pdf"),
    device = cairo_pdf,
    units = "cm",
    width = 13.1, height = 8, dpi = 300
)
```

## Plot energy estimation comparison by estimation method
```{r load-data-energy-estimation-comparison, echo=FALSE}
energy_estimation_comparison <- read_parquet("data/analysis/processed/energy-estimation-results.gzip")
```

```{r plot-energy-estimation-comparison}
annotation_size <- 8 / ggplot2::.pt # Convert to relative size
ga_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`estimated total energy (kJ) (GA)`
)^2
ga_r2 <- round(ga_r2, 3)

ga_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `estimated total energy (kJ) (GA)`)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "#E41A1C", linewidth = .8) +
    geom_smooth(method = "lm", color = "#377EB8", se = FALSE, linewidth = .8) +
    labs(
        x = element_blank(),
        y = "Predicted energy (kJ)",
        title = "Green Algorithms"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", ga_r2), color = "#377EB8", size = annotation_size)

mlco2_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`estimated total energy (kJ) (MLCO2)`
)^2
mlco2_r2 <- round(mlco2_r2, 3)
mlco2_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `estimated total energy (kJ) (MLCO2)`)) +
    geom_point(alpha = 0.5) +
    geom_smooth(aes(color = "Fitted"), method = "lm", se = FALSE, linewidth = .8) +
    geom_line(aes(y = `true energy (kJ)`, color = "Diagonal"), linewidth = .8) +
    labs(
        x = "True energy (kJ)",
        y = "Predicted energy (kJ)",
        title = "MLCO2 Calculator"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", mlco2_r2), color = "#377EB8", size = annotation_size) +
    scale_color_manual(
        name = NULL,
        values = c("Diagonal" = "#E41A1C", "Fitted" = "#377EB8"),
        breaks = c("Diagonal", "Fitted"),
        labels = c("x=y", "Fitted")
    ) +
    guides(
        color = guide_legend(ncol = 1)
    ) +
    theme(
        legend.position = "inside",
        legend.justification = c("right", "bottom"),
        legend.box.just = "left",
        legend.margin = margin(0, 0, 0, 0),
        legend.background = element_rect(fill = "transparent")
    )

online_power_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`estimated total energy (kJ) (online power-based)`
)^2
online_power_r2 <- round(online_power_r2, 3)
online_power_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `estimated total energy (kJ) (online power-based)`, yend = 2000)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "#E41A1C", linewidth = .8) +
    geom_smooth(method = "lm", color = "#377EB8", se = FALSE, linewidth = .8) +
    labs(
        x = "True energy (kJ)",
        y = "Predicted energy (kJ)",
        title = "STEP-P"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", online_power_r2), color = "#377EB8", size = annotation_size)

online_epoch_energy_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`estimated total energy (kJ) (online epoch-energy-based)`
)^2
online_epoch_energy_r2 <- round(online_epoch_energy_r2, 3)
online_epoch_energy_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `estimated total energy (kJ) (online epoch-energy-based)`, yend = 2000)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "#E41A1C", linewidth = .8) +
    geom_smooth(method = "lm", color = "#377EB8", se = FALSE, linewidth = .8) +
    labs(
        x = "True energy (kJ)",
        y = "Predicted energy (kJ)",
        title = "STEP-E"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", online_epoch_energy_r2), color = "#377EB8", size = annotation_size)

offline_power_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`power estimator energy (kJ)`
)^2
offline_power_r2 <- round(offline_power_r2, 3)
offline_power_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `power estimator energy (kJ)`, yend = 2000)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "#E41A1C", linewidth = .8) +
    geom_smooth(method = "lm", color = "#377EB8", se = FALSE, linewidth = .8) +
    labs(
        x = "True energy (kJ)",
        y = "Predicted energy (kJ)",
        title = "PRE-P"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", offline_power_r2), color = "#377EB8", size = annotation_size)

offline_epoch_energy_r2 <- cor(
    energy_estimation_comparison$`true energy (kJ)`,
    energy_estimation_comparison$`energy estimator energy (kJ)`
)^2
offline_epoch_energy_r2 <- round(offline_epoch_energy_r2, 3)
offline_epoch_energy_plot <- ggplot(energy_estimation_comparison, aes(x = `true energy (kJ)`, y = `energy estimator energy (kJ)`, yend = 2000)) +
    geom_point(alpha = 0.5) +
    geom_abline(slope = 1, intercept = 0, color = "#E41A1C", linewidth = .8) +
    geom_smooth(method = "lm", color = "#377EB8", se = FALSE, linewidth = .8) +
    labs(
        x = "True energy (kJ)",
        y = "Predicted energy (kJ)",
        title = "PRE-E"
    ) +
    # Add R2 value to the plot
    annotate("text", x = 200, y = 1500, label = paste("R² =", offline_epoch_energy_r2), color = "#377EB8", size = annotation_size)

combined_energy_estimation_plot <- ga_plot + mlco2_plot + online_power_plot + online_epoch_energy_plot + offline_power_plot + offline_epoch_energy_plot +
    plot_layout(ncol = 2, nrow = 3, axes = "collect")

combined_energy_estimation_plot

ggsave(
    plot = combined_energy_estimation_plot & pub_theme,
    filename = file.path(fig_dir, "energy-estimation-methods-evaluation.pdf"),
    device = cairo_pdf,
    units = "cm",
    width = 13.1, height = 12, dpi = 300
)
```
