OUTPUT_DIR : 'out'
FIGURES_DIR: 'out/figures'
REPORTS_DIR: 'reports'
DATA_DIR: 'data'
DATASET_DIR: 'data/dataset'
METRICS_DIR: 'data/metrics'
MODELS_DIR: 'models'

INFERENCE_MODEL: 'xception-occupancy'

DEBUG: false
