OUTPUT_DIR : 'out'
REPORTS_DIR: 'reports'
FIGURES_DIR: 'reports/figures'
DATA_DIR: 'data'
DATASET_DIR: 'data/dataset'
METRICS_DIR: 'data/metrics'
MODELS_DIR: 'models'

INFERENCE_MODEL: 'xception-occupancy'

DEBUG: false
